name: base
channels:
  - defaults
  - conda-forge
dependencies:
  #- python=3.9
  # - conda-forge::opencv
  - seaborn
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - jupyterlab
  - matplotlib
  - plotly
  - tqdm
  - pip
  - pip:
    - pytube
    - ffmpeg-python
    - open3d
    - opencv-python
